export const assessmentNames = [
    'HTML Basics Quiz',
    'CSS Fundamentals Exam',
    'JavaScript Syntax Assessment',
    'Responsive Web Design Project',
    'DOM Manipulation Task',
    'Git Version Control Test',
    'Server-Side Scripting Quiz',
    'Database Design Assignment',
    'User Authentication Project',
    'API Integration Challenge',
    'Front-End Framework Assessment',
    'Back-End Development Task',
    'Full Stack Project Proposal',
    'Test-Driven Development Exam',
    'Deployment and Hosting Review',
    'Performance Optimization Task',
    'Error Handling and Debugging Quiz',
    'Security Vulnerability Assessment',
    'Continuous Integration Test',
    'UX/UI Design Evaluation',
    'Agile Software Development Project',
    'RESTful API Development Task',
    'Database Migration Assessment',
    'Web Accessibility Review',
    'Scalability and Load Testing Exam',
    'Real-time Communication Project',
    'Web Scraping Challenge',
    'Serverless Architecture Assessment',
    'Cloud Deployment Task',
    'Code Review and Refactoring Quiz',
    'DevOps Automation Exam',
    'Docker Containerization Project',
    'Microservices Architecture Task',
    'Performance Monitoring Assessment',
    'Mobile App Integration Review',
    'GraphQL Implementation Quiz',
    'Cross-Browser Compatibility Task',
    'Progressive Web App (PWA) Project',
    'DevSecOps Assessment',
    'Final Full Stack Application Evaluation',
]
export const projectNames = [
    'Personal Portfolio Website',
    'Static Restaurant Website',
    'Weather App',
    'Todo List Application',
    'E-commerce Website',
    'Social Media Clone',
    'Blogging Platform',
    'Music Streaming App',
    'Online Marketplace',
    'Job Board Platform',
    'Recipe Sharing Website',
    'Travel Planner',
    'Fitness Tracking Application',
    'Real Estate Listing Website',
    'Chat Application',
    'Online Banking System',
    'Event Management Platform',
    'Crowdfunding Platform',
    'Task Management Tool',
    'Book Recommendation Website',
    'Car Rental App',
    'Movie Review Platform',
    'Online Learning Management System',
    'Restaurant Reservation System',
    'Issue Tracker',
    'Ticket Booking App',
    'Pet Adoption Platform',
    'Stock Trading Simulator',
    'Event Ticketing System',
    'Video Streaming Platform',
    'Carpooling App',
    'Charity Donation Website',
    'Sports League Management System',
    'Flight Booking App',
    'Property Rental Marketplace',
    'Music Event Finder',
    'Job Search Platform',
    'Online Auction Site',
    'Health and Wellness Tracker',
    'Language Learning App',
    'Event Reminder Application',
    'Social Networking Platform',
]

export const assignmentNames = [
    'HTML Basics Assignment',
    'CSS Styling Assignment',
    'JavaScript Fundamentals Assignment',
    'Responsive Web Design Task',
    'DOM Manipulation Assignment',
    'Git Version Control Exercise',
    'Server-Side Scripting Assignment',
    'Database Design Project',
    'User Authentication Task',
    'API Integration Assignment',
    'Front-End Framework Exercise',
    'Back-End Development Task',
    'Full Stack Project Proposal',
    'Test-Driven Development Assignment',
    'Deployment and Hosting Project',
    'Performance Optimization Task',
    'Error Handling and Debugging Assignment',
    'Security Vulnerability Assessment',
    'Continuous Integration Exercise',
    'UX/UI Design Evaluation',
    'Agile Software Development Project',
    'RESTful API Development Task',
    'Database Migration Assignment',
    'Web Accessibility Task',
    'Scalability and Load Testing Project',
    'Real-time Communication Assignment',
    'Web Scraping Task',
    'Serverless Architecture Project',
    'Cloud Deployment Assignment',
    'Code Review and Refactoring Task',
    'DevOps Automation Assignment',
    'Docker Containerization Project',
    'Microservices Architecture Task',
    'Performance Monitoring Assignment',
    'Mobile App Integration Project',
    'GraphQL Implementation Task',
    'Cross-Browser Compatibility Assignment',
    'Progressive Web App (PWA) Project',
    'DevSecOps Assessment',
    'Final Full Stack Application Evaluation',
]
